name: Multiple jobs

on:
  push:

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a Dragon ....RAWR" >> dragon.txt

      - name: Test file Exists
        run: grep -i "dragon" dragon.txt
        
      - name: read  file
        run: cat dragon.txt
        
      - name: checkout repo files
        run: ls
